L = {} -- Swedish Content Strings by Moka

///////////////////// -- [[ Special Delivery ]] --
-- Weapons
ws = "tacrp_sd_"
w = ws .. "1022"
L["wep." .. w .. ".name.full"] = "Ruger 10/22"
L["wep." .. w .. ".name"] = "10/22"
L["wep." .. w .. ".desc"] = "Ultralätt plink-gevär. Väldigt träffsäker och lätt att hantera, men den är knappt dödlig om du inte träffar huvudet."
L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
L["wep." .. w .. ".credits"] = "Tillgångar: No More Room in Hell \nAnimationer: Tactical Intervention"

w = ws .. "1858"
L["wep." .. w .. ".name.full"] = "Remington 1858 Army"
L["wep." .. w .. ".name"] = "Army"
L["wep." .. w .. ".desc"] = "Antik tändhattsrevolver med tuff prestanda på nära håll, men är inte så snabb att skjuta. Perfekt för cowboy-rollspel."
L["wep." .. w .. ".desc.quote"] = "\"Skicka hit whiskey:n!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
L["wep." .. w .. ".credits"] = "Tillgångar: Nimrod Hempel (Fistful of Frags) \nAnimationer: CyloWalker \nSnabbkast & Närstrid Animationer: speedonerd"

w = ws .. "aac_hb"
L["wep." .. w .. ".name.full"] = "AAC Honey Badger"
L["wep." .. w .. ".name"] = "Honey Badger"
L["wep." .. w .. ".desc"] = "En lätt automatkarbin med inbyggd ljuddämpare. Kraftfull på nära distanser och har inga synliga spårljus, men har dålig prestanda vid räckvidd."
L["wep." .. w .. ".trivia.manufacturer"] = "AAC"
L["wep." .. w .. ".credits"] = "Modell: Hyper \nAnimationer: Tactical Intervention"

w = ws .. "bizon"
L["wep." .. w .. ".name.full"] = "PP-19 Bizon"
L["wep." .. w .. ".name"] = "Bizon"
L["wep." .. w .. ".desc"] = "AK-härledd kulsprutepistol med hög kapacitets spiralmagasin. Ganska svag men lätt att kontrollera och hantera."
L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Milo \nLjud: Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "contender"
L["wep." .. w .. ".name.full"] = "T/C G2 Contender"
L["wep." .. w .. ".name"] = "Contender"
L["wep." .. w .. ".desc"] = "Enkelskott jaktpistol. Träffsäker, kompakt och dödlig, så bäst att det enda skottet träffar. \nUtrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Vet du vad jag hatar? Två sorters folk...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Thompson/Center"
L["wep." .. w .. ".credits"] = "Modell: kriboez, Doktor haus \nTexturer: cR45h, syncing, tenoyl, Ultimately \nLjud: Doktor haus \nAnimationer: 8Z, speedonerd"

w = ws .. "db"
L["wep." .. w .. ".name.full"] = "Stoeger Double Defense"
L["wep." .. w .. ".name"] = "Double Defense"
L["wep." .. w .. ".desc"] = "Modern tillverkad kort dubbelpipig hagelbössa. Lätt att hantera, pålitlig och dödlig på nära avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Eat leaden death, demon.\"" --To be translated
L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
L["wep." .. w .. ".credits"] = "Modell: Counter-Strike: Online 2 \nLjud: Navaro & Vunsunta \nAnimationer: speedonerd & 8Z"

w = ws .. "delisle"
L["wep." .. w .. ".name.full"] = "De Lisle-Karbin"
L["wep." .. w .. ".name"] = "De Lisle"
L["wep." .. w .. ".desc"] = "Ljuddämpad pistolkaliber cylinderrepeterkarbin. Ett av dem tystaste eldvapnen någonsin, dess subsoniska skott har inga spårljus men färdas ganska sakta."
L["wep." .. w .. ".desc.quote"] = "Sköts in i Thames-floden, inte en själ hörde det."
L["wep." .. w .. ".trivia.manufacturer"] = "Sterling Armaments"
L["wep." .. w .. ".credits"] = "Modell: RedRougeXIII \nTexturer: Storm (snällt fixad av Unselles) \nAnimationer: Tactical Intervention"

w = ws .. "dual_1911"
L["wep." .. w .. ".name"] = "Dueling Wyverns"
L["wep." .. w .. ".desc"] = "Ett par pråliga, specialbeställda gyllene M1911-pistoler komplett med wyvern-graverat grepp. Träffar hårt, men dess låga kapacitet kan skada."
L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
L["wep." .. w .. ".credits"] = "Modell: Schmung \nTexturer: Millenia \nAnimationer: Tactical Intervention"

w = ws .. "dual_degala"
L["wep." .. w .. ".name"] = "Dual Eagles"
L["wep." .. w .. ".desc"] = "Ett par pråliga guldbelagda Desert Eagles, som om en inte räckte. \nDubbelt så otrolig eldkraft, dubbelt otroligt hög rekyl."
L["wep." .. w .. ".desc.quote"] = "\"Mitt blod... på deras händer.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
L["wep." .. w .. ".credits"] = "Modell: Hav0c & Stoke \nTexturer: The_Tub & Stoke \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "dual_ppk"
L["wep." .. w .. ".name"] = "Dual Agents"
L["wep." .. w .. ".desc"] = "Ett par ljuddämpade PPK-pistoler. Snabba och träffsäkra, men den låga kapaciteten och måttliga skadan kräver ett skarpt öga och avtryckare disciplin."
L["wep." .. w .. ".desc.quote"] = "Du får fan inte välja Oddjob."
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Kimono \nLjud: HK & Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "dual_usp"
L["wep." .. w .. ".name"] = "Dual Matches"
L["wep." .. w .. ".desc"] = "Ett par pistoler snattade från ett par döda metro-poliser. Måttlig skada och kapacitet, men rejälva och inte snabba att skjutas."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Silvio Dante & Twinke Masta \nTexturer: LoneWolf \nAnimationer: Tactical Intervention"

w = ws .. "dual_uzis"
L["wep." .. w .. ".name"] = "Dual Uzis"
L["wep." .. w .. ".desc"] = "Ett par helautomatiska Micro Uzi:n. Vet inte hur exakt du förväntar dig att träffa något med dessa, men gör som du vill."
L["wep." .. w .. ".desc.quote"] = "\"Kommer slå dig med så många vänstra att du kommer be om en höger!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
L["wep." .. w .. ".credits"] = "Modell: BrainBread 2 \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "dualies"
L["wep." .. w .. ".name"] = "Dueling Dragons"
L["wep." .. w .. ".desc"] = "Ett par anpassade pistoler med en tvåfärgad finish och drakar utsmyckade på greppen. Snabbt hantering och måttlig rekylkontroll men låg eldkraft."
L["wep." .. w .. ".desc.quote"] = "\"Jag tog bort fingret från avtryckaren. Då var det slut.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Modell: Spydr \nTexturer: NCFurious \nAnimationer: Tactical Intervention"

w = ws .. "famas"
L["wep." .. w .. ".name"] = "FAMAS F1"
L["wep." .. w .. ".desc"] = "Bullpup-gevär med salvoeld som används av franska armén. Hög eldhastighet och bra träffsäkerhet, begränsad endast av den undermåliga magasinkapaciteten och ganska intensiva rekylen. \nHar ett skjutstöd tack vare typisk fransk anledning."
L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
L["wep." .. w .. ".credits"] = "Modell: SnipaMasta \nTexturer: SnipaMasta, Fnuxray \nAnimationer: speedonerd"

w = ws .. "famas_g2"
L["wep." .. w .. ".name"] = "FAMAS G2"
L["wep." .. w .. ".desc"] = "Bullpup-gevär med extremt snabb eldhastighet som används av franska marinen. Tillgång till automateld, men salvoeld eller det inbyggda skjutstödet rekommenderas."
L["wep." .. w .. ".desc.quote"] = "\"Gud har verkligen sinne för humör.\""
L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
L["wep." .. w .. ".credits"] = "Modell: SnipaMasta \nTexturer: SnipaMasta, Fnuxray \nAnimationer: speedonerd"

w = ws .. "g3"
L["wep." .. w .. ".name.full"] = "HK G3A3"
L["wep." .. w .. ".name"] = "G3A3"
L["wep." .. w .. ".desc"] = "Träffsäkert och tungt stridsgevär med en ganska hanterbart automateldläge men sölig hantering."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Tillgångar: Firearms: Source \nLjud: Nightmare Mutant & FA:S2 \nAnimationer: Tactical Intervention"

w = ws .. "groza"
L["wep." .. w .. ".name.full"] = "OTs-14 \"Groza\""
L["wep." .. w .. ".name"] = "Groza-4"
L["wep." .. w .. ".desc"] = "Bullpup-gevär med inbyggd ljuddämpare gjord från omkonfigurerad AK. Svag men har bra hantering och stabilitet utan synliga spårljus."
L["wep." .. w .. ".desc.quote"] = "\"Bort härifrån, Stalker.\""
L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
L["wep." .. w .. ".credits"] = "Modell: Teh Snake, redigerad av speedonerd \nTexturer: Teh Snake \nLjud: Teh Snake & speedonerd \nAnimationer: speedonerd"

w = ws .. "gyrojet"
L["wep." .. w .. ".name.full"] = "MBA Gyrojet"
L["wep." .. w .. ".name"] = "Gyrojet"
L["wep." .. w .. ".desc"] = "Experimentellt vapen som skjuter självgående minirobotar. Dem må vara kraftfulla, men dem har hög chans att inte kunna skjutas."
L["wep." .. w .. ".desc.quote"] = "\"Undrar hur mycket av dess rester går för på Tradera.\"" -- "Tradera" is Swedish Ebay... -ish.
L["wep." .. w .. ".trivia.manufacturer"] = "MBAssociates"
L["wep." .. w .. ".credits"] = "Modell & Texturer: RedRougeXIII \nLjud: speedonerd, Tactical Intervention \nAnimationer: speedonerd"

w = ws .. "m1carbine"
L["wep." .. w .. ".name"] = "M1-Karbin"
L["wep." .. w .. ".desc"] = "Halvautomatisk karbin från andra världskriget. Gjord som ett försvarsvapen för understödstrupper, den är träffsäker och lätt men har måttlig stoppkraft."
L["wep." .. w .. ".desc.quote"] = "\"Flash.\" \"Thunder.\""
L["wep." .. w .. ".trivia.manufacturer"] = "General Motors"
L["wep." .. w .. ".credits"] = "Modell & Texturer: KnechtRuprecht \nLjud: NightmareMutant \nAnimationer: Tactical Intervention"

w = ws .. "mp40"
L["wep." .. w .. ".name.full"] = "Steyr MP40"
L["wep." .. w .. ".name"] = "MP40"
L["wep." .. w .. ".desc"] = "Kulsprutepistol från andra världskriget med låg eldhastighet och lätt rekyl. Trots dess ålder så visar den sig i många krig än idag."
L["wep." .. w .. ".desc.quote"] = "\"Hans, ditt kaffe suger. Jag dricker inte den skiten.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr-Mannlicher"
L["wep." .. w .. ".credits"] = "Modell: Soul-Slayer \nTexturer: Kimono \nLjud: Futon & Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "pkm"
L["wep." .. w .. ".name"] = "PKM"
L["wep." .. w .. ".desc"] = "Generell kulspruta med möjlighet av intensiv täckande eld. Hög kapacitet och skada men är väldigt, väldigt tung."
L["wep." .. w .. ".trivia.manufacturer"] = "Degtyaryov Plant"
L["wep." .. w .. ".credits"] = "Tillgångar: Call to Arms \nLjud: NightmareMutant & speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "ppk"
L["wep." .. w .. ".name.full"] = "Walther PPK"
L["wep." .. w .. ".name"] = "PPK"
L["wep." .. w .. ".desc"] = "Kompakt fickpistol med låg kapacitet gjord känd av filmer. Bäst gjord för självförsvar på nära avstånd."
L["wep." .. w .. ".desc.quote"] = "\"Upprörande. Väldigt upprörande.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Kimono \nLjud: HK & Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "superx3"
L["wep." .. w .. ".name.full"] = "Winchester Super X3"
L["wep." .. w .. ".name"] = "Super X3"
L["wep." .. w .. ".desc"] = "Civil sporthagelbössa tillverkad för prestanda. Lång pipa och tävlingsgjord choke erbjuder bra träffsäkerhet och räckvidd, men dålig hantering."
L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
L["wep." .. w .. ".credits"] = "Model, Textures & Sound: No More Room in Hell \nAnimationer: Tactical Intervention"

w = ws .. "thompson"
L["wep." .. w .. ".name.full"] = "M1A1 Thompson"
L["wep." .. w .. ".name"] = "Thompson"
L["wep." .. w .. ".desc"] = "Kulsprutepistol från andra världskriget med kraftiga trädelar. Har imponerande stoppkraft på nära avstånd, men är ganska tung."
L["wep." .. w .. ".desc.quote"] = "\"Ät bly, tyskjävlar!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Auto-Ordnance Company"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter-Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "tt33"
L["wep." .. w .. ".name.full"] = "Tokarev TT-33"
L["wep." .. w .. ".name"] = "TT-33"
L["wep." .. w .. ".desc"] = "Antik pistol från bakom järnridån. Hög räckvidd och penetrationsförmåga, men har pålitlighetsproblem tack vare dess ålder."
L["wep." .. w .. ".desc.quote"] = "\"Du hade kanske föredragit att undvika röda tejpen?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".credits"] = "Modell: Mr.Rifleman \nTexturer: BuLL5H1T & Mr.Rifleman \nLjud: NightmareMutant \nAnimationer: Tactical Intervention"

w = ws .. "vz58"
L["wep." .. w .. ".name.full"] = "Sa vz. 58"
L["wep." .. w .. ".name"] = "vz. 58"
L["wep." .. w .. ".desc"] = "Automatkarbin med hög skada och utmärkt penetrationsförmåga, konverterad till halvautomat för civila marknader."
L["wep." .. w .. ".desc.quote"] = "Trots dess utseende så är det definitivt inte en AK."
L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
L["wep." .. w .. ".credits"] = "Model, Textures & Ljud: No More Room in Hell \nAnimationer: Tactical Intervention"

w = ws .. "wa2000"
L["wep." .. w .. ".name.full"] = "Walther WA 2000"
L["wep." .. w .. ".name"] = "WA 2000"
L["wep." .. w .. ".desc"] = "Elegant bullpup-krypskyttegevär med hög skada och eldhastighet. \nUtrustat med ett 12x kikarsikte som standard."
L["wep." .. w .. ".desc.quote"] = "\"Namn är för vänner, och jag vill inte ha någon.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Tillgångar: Alliance of Valiant Arms \nEgentligen portat till CS 1.6 av GR_Lucia \nLjud: HK & Vunsunta \nAnimationer: Tactical Intervention, redigerad av speedonerd"

-- Attachments (sd)
-- L["att.trigger_dual_uzis_semi.name.full"] = "att.trigger_semi.name.full"
-- L["att.trigger_dual_uzis_semi.name"] = "att.trigger_semi.name"
-- L["att.trigger_dual_uzis_semi.desc"] = "att.trigger_semi.desc"

L["att.tac_1858_spin.name.full"] = "Revolver Spin"
L["att.tac_1858_spin.name"] = "Spin"
L["att.tac_1858_spin.desc"] = "wheeeeeeeeeeeee"

L["att.optic_m1_scope.name.full"] = "M1-Karbin 3,5x24-Sikte"
L["att.optic_m1_scope.name"] = "3,5x Sikte"
L["att.optic_m1_scope.desc"] = "Riktmedel gjord med speciell montering till M1-Karbinen."

L["att.optic_delisle_scope.name.full"] = "De Lisle 4x24-Sikte"
L["att.optic_delisle_scope.name"] = "4x Sikte"
L["att.optic_delisle_scope.desc"] = "Riktmedel med speciell montering till De Lisle."

L["att.muzz_supp_assassin.name.full"] = "Lönnmördare Ljuddämpare"
L["att.muzz_supp_assassin.name"] = "L. Ljuddämp"
L["att.muzz_supp_assassin.desc"] = "Förlängd ljuddämpare som drastiskt förbättrar räckvidden med kostnad på stabilitet."

L["att.ammo_gyrojet_ratshot.name.full"] = "13 mm Råttskott Mini-Robotar"
L["att.ammo_gyrojet_ratshot.name"] = "Råttskott"
L["att.ammo_gyrojet_ratshot.desc"] = "Närhetsaktiverade mini-splittergranatrobotar. Mot gnagare av oväntad storlek."

L["att.ammo_gyrojet_pipe.name.full"] = "15 mm Förstärkta Rörgranater"
L["att.ammo_gyrojet_pipe.name"] = "Rör"
L["att.ammo_gyrojet_pipe.desc"] = "Tunga tidsinställda granater. Direkta träffar sprängs omedelbart."

L["att.ammo_gyrojet_lv.name.full"] = "11 mm Låg Hastighets Mini-Robotar"
L["att.ammo_gyrojet_lv.name"] = "LH"
L["att.ammo_gyrojet_lv.desc"] = "Projektiler med sänkt diameter och hastighet som har ett mindre synligt spår."

L["att.ammo_gyrojet_he.name.full"] = "13 mm Mini-Splittergranatrobotar"
L["att.ammo_gyrojet_he.name"] = "SGR"
L["att.ammo_gyrojet_he.desc"] = "Projektil med en mindre sprängladdning istället för patronhuvud."

L["att.ammo_1858_45colt.name.full"] = "Remington 1858 .45 Colt Konvertering"
L["att.ammo_1858_45colt.name"] = ".45 Colt"
L["att.ammo_1858_45colt.desc"] = "Patronkonvertering skjuter större, mer kraftfulla, men mindre pålitliga skott."

L["att.ammo_1858_36perc.name.full"] = "Remington 1858 .36 Tändhattkonvertering"
L["att.ammo_1858_36perc.name"] = ".36 Tändhatt"
L["att.ammo_1858_36perc.desc"] = "Kaliberkonvertering skjuter mindre skott med högre räckvidd."

L["att.procon.yeehaw"] = "yeeeeeeeeeeeeehawwwwwwwwww"