L = {} -- English Content Strings

///////////////////// -- [[ Special Delivery ]] --
-- Weapons
ws = "tacrp_sd_"
w = ws .. "1022"
L["wep." .. w .. ".name.full"] = "Ruger 10/22"
L["wep." .. w .. ".name"] = "10/22"
L["wep." .. w .. ".desc"] = "Ultra-lightweight plinking rifle. Highly accurate and easy to handle, but is barely lethal unless scoring a headshot."
L["wep." .. w .. ".desc.quote"] = "Better than your bare hands."
L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
L["wep." .. w .. ".credits"] = "Assets: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "1858"
L["wep." .. w .. ".name.full"] = "Remington 1858 Army"
L["wep." .. w .. ".name"] = "Army"
L["wep." .. w .. ".desc"] = "Antique percussion revolver packing a punch up close, but is terribly slow to shoot. Suitable for cowboy roleplay."
L["wep." .. w .. ".desc.quote"] = "\"Pass the whiskey!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
L["wep." .. w .. ".credits"] = "Assets: Nimrod Hempel (Fistful of Frags) \nAnimations: CyloWalker \nQuickthrow & melee animations: speedonerd"

w = ws .. "aac_hb"
L["wep." .. w .. ".name.full"] = "AAC Honey Badger"
L["wep." .. w .. ".name"] = "Honey Badger"
L["wep." .. w .. ".desc"] = "A lightweight assault rifle with an integral suppressor. Powerful in close quarters and has no visible tracer, but has poor performance at range."
L["wep." .. w .. ".desc.quote"] = "\"We're Ghosts, Merrick. We finish the mission.\""
L["wep." .. w .. ".trivia.manufacturer"] = "AAC"
L["wep." .. w .. ".credits"] = "Model: Hyper \nAnimations: Tactical Intervention"

w = ws .. "bizon"
L["wep." .. w .. ".name.full"] = "PP-19 Bizon"
L["wep." .. w .. ".name"] = "Bizon"
L["wep." .. w .. ".desc"] = "AK-derrivative SMG with a high-capacity helical magazine.  Pretty weak but easy to control and handle."
L["wep." .. w .. ".desc.quote"] = "\"NEEEJJJJ!!!! FAN BATTLE-SCARRED PP-BIZONNNN!!!! FITTAAAA!!!!!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Milo \nSounds: Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "contender"
L["wep." .. w .. ".name.full"] = "T/C G2 Contender"
L["wep." .. w .. ".name"] = "Contender"
L["wep." .. w .. ".desc"] = "Single-shot hunting pistol. Accurate, compact and lethal, so you better make that one round count. \nEquipped with a 6x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"You know what I hate? Two groups of people...\""
L["wep." .. w .. ".trivia.manufacturer"] = "Thompson/Center"
L["wep." .. w .. ".credits"] = "Model: kriboez, Doktor haus \nTextures: cR45h, syncing, tenoyl, Ultimately \nSounds: Doktor haus \nAnimations: 8Z, speedonerd"

w = ws .. "db"
L["wep." .. w .. ".name.full"] = "Stoeger Double Defense"
L["wep." .. w .. ".name"] = "Double Defense"
L["wep." .. w .. ".desc"] = "Modern-production short double-barrel shotgun.  Easy to handle, reliable and deadly in close quarters."
L["wep." .. w .. ".desc.quote"] = "\"Eat leaden death, demon.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
L["wep." .. w .. ".credits"] = "Model: Counter-Strike: Online 2 \nSounds: Navaro & Vunsunta \nAnimations: speedonerd & 8Z"

w = ws .. "delisle"
L["wep." .. w .. ".name.full"] = "De Lisle Carbine"
L["wep." .. w .. ".name"] = "De Lisle"
L["wep." .. w .. ".desc"] = "Pistol caliber bolt-action carbine with an integrated suppressor. One of the quietest firearms ever made, its subsonic rounds have no tracer but travel slowly."
L["wep." .. w .. ".desc.quote"] = "Fired into the River Thames, not a soul heard it."
L["wep." .. w .. ".trivia.manufacturer"] = "Sterling Armaments"
L["wep." .. w .. ".credits"] = "Model: RedRougeXIII \nTextures: Storm (lovingly fixed by Unselles) \nAnimations: Tactical Intervention"

w = ws .. "dual_1911"
L["wep." .. w .. ".name"] = "Dueling Wyverns"
L["wep." .. w .. ".desc"] = "A pair of gaudy, custom made golden M1911 pistols complete with wyvern-engraved grip. Hits hard, but its low capacity can be hurting."
L["wep." .. w .. ".desc.quote"] = "\"Engravings... give you no tactical advantage whatsoever.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
L["wep." .. w .. ".credits"] = "Model: Schmung \nTextures: Millenia \nAnimations: Tactical Intervention"

w = ws .. "dual_degala"
L["wep." .. w .. ".name"] = "Dual Eagles"
L["wep." .. w .. ".desc"] = "Pair of gaudy gold-coated Desert Eagles, as if one wasn't enough. \nTwice the insane firepower, twice the insane recoil."
L["wep." .. w .. ".desc.quote"] = "\"My blood...on their hands.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
L["wep." .. w .. ".credits"] = "Model: Hav0c & Stoke \nTextures: The_Tub & Stoke \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "dual_ppk"
L["wep." .. w .. ".name"] = "Dual Agents"
L["wep." .. w .. ".desc"] = "A pair of suppressed PPK pistols. Swift and accurate, but the low capacity and mediocre damage demands a sharp eye and trigger discpline."
L["wep." .. w .. ".desc.quote"] = "You better not be picking Oddjob."
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dual_usp"
L["wep." .. w .. ".name"] = "Dual Matches"
L["wep." .. w .. ".desc"] = "Pair of pistols pilfered from a pair of dead metrocops. Decent damage and capacity but hefty and slow to fire."
L["wep." .. w .. ".desc.quote"] = "If Gordon was smart, he would do this."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Model: Silvio Dante & Twinke Masta \nTextures: LoneWolf \nAnimations: Tactical Intervention"

w = ws .. "dual_uzis"
L["wep." .. w .. ".name"] = "Dual Uzis"
L["wep." .. w .. ".desc"] = "Pair of full-auto Micro Uzis. I don't know how you expect to hit anything with this getup, but you do you I guess."
L["wep." .. w .. ".desc.quote"] = "\"I'll hit you with so many rights you'll be begging for a left!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
L["wep." .. w .. ".credits"] = "Model: BrainBread 2 \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dualies"
L["wep." .. w .. ".name"] = "Dueling Dragons"
L["wep." .. w .. ".desc"] = "Pair of customized pistols with a two-tone finish and dragons emblazoned on the grips.  Swift handling and decent recoil control but low stopping power."
L["wep." .. w .. ".desc.quote"] = "\"I released my finger from the trigger, and it was over.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Model: Spydr \nTextures: NCFurious \nAnimations: Tactical Intervention"

w = ws .. "famas"
L["wep." .. w .. ".name"] = "FAMAS F1"
L["wep." .. w .. ".desc"] = "Burst-fire French bullpup rifle. High rate of fire and great accuracy limited by its odd magazine capacity and intense recoil. Has a bipod for esoteric French reasons."
L["wep." .. w .. ".desc.quote"] = "if 3 round burst, why mag not divide by 3?"
L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "famas_g2"
L["wep." .. w .. ".name"] = "FAMAS G2"
L["wep." .. w .. ".desc"] = "Bullpup rifle with a blazing fast firerate, used by the French Navy. While capable of automatic fire, using burst-fire or the built-in bipod is recommended."
L["wep." .. w .. ".desc.quote"] = "\"God's got a sense of humor, alright.\""
L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "g3"
L["wep." .. w .. ".name.full"] = "HK G3A3"
L["wep." .. w .. ".name"] = "G3A3"
L["wep." .. w .. ".desc"] = "Precise heavy battle rifle with a somewhat managable automatic firemode but slow handling."
L["wep." .. w .. ".desc.quote"] = "\"Yeah, well, we can't all be Schwarzenegger.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nSounds: Nightmare Mutant & FA:S2 \nAnimations: Tactical Intervention"

w = ws .. "groza"
L["wep." .. w .. ".name.full"] = "OTs-14 \"Groza\""
L["wep." .. w .. ".name"] = "Groza-4"
L["wep." .. w .. ".desc"] = "Integrally-suppressed bullpup made from a reconfigured AK. Weak, but has great handling and stability and has no visible tracers."
L["wep." .. w .. ".desc.quote"] = "\"Get out of here, Stalker.\""
L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
L["wep." .. w .. ".credits"] = "Model: Teh Snake, edited by speedonerd \nTextures: Teh Snake \nSounds: Teh Snake & speedonerd \nAnimations: speedonerd"

w = ws .. "gyrojet"
L["wep." .. w .. ".name.full"] = "MBA Gyrojet"
L["wep." .. w .. ".name"] = "Gyrojet"
L["wep." .. w .. ".desc"] = "Experimental weapon firing self-propelled mini-rockets. While they are powerful, the rounds are prone to failure."
L["wep." .. w .. ".desc.quote"] = "\"I wonder how much his remains would go for on Ebay.\""
L["wep." .. w .. ".trivia.manufacturer"] = "MBAssociates"
L["wep." .. w .. ".credits"] = "Model & Textures: RedRougeXIII \nSounds: speedonerd, Tactical Intervention \nAnimations: speedonerd"

w = ws .. "m1carbine"
L["wep." .. w .. ".name"] = "M1 Carbine"
L["wep." .. w .. ".desc"] = "WW2-era semi-auto carbine. Intended as a defensive weapon for support troops, it is accurate and lightweight but has mediocre power."
L["wep." .. w .. ".desc.quote"] = "\"Flash.\" \"Thunder.\""
L["wep." .. w .. ".trivia.manufacturer"] = "General Motors"
L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "mp40"
L["wep." .. w .. ".name.full"] = "Steyr MP40"
L["wep." .. w .. ".name"] = "MP40"
L["wep." .. w .. ".desc"] = "WW2-era SMG with a low rate of fire and light recoil. Despite its age, it still shows up in many warzones today."
L["wep." .. w .. ".desc.quote"] = "\"Hans, your coffee sucks. I'm not drinking that crap.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Steyr-Mannlicher"
L["wep." .. w .. ".credits"] = "Model: Soul-Slayer \nTextures: Kimono \nSounds: Futon & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "pkm"
L["wep." .. w .. ".name"] = "PKM"
L["wep." .. w .. ".desc"] = "General-purpose machine gun capable of intense suppressive fire. High capacity and damage but is very, very bulky."
L["wep." .. w .. ".desc.quote"] = "Notably seen atop Mercedes-Benz G-Wagens."
L["wep." .. w .. ".trivia.manufacturer"] = "Degtyaryov Plant"
L["wep." .. w .. ".credits"] = "Assets: Call to Arms \nSounds: NightmareMutant & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "ppk"
L["wep." .. w .. ".name.full"] = "Walther PPK"
L["wep." .. w .. ".name"] = "PPK"
L["wep." .. w .. ".desc"] = "Compact, low-capacity pocket pistol made famous by the movies. Best suited for close range self defense."
L["wep." .. w .. ".desc.quote"] = "\"Shocking. Positively shocking.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "superx3"
L["wep." .. w .. ".name.full"] = "Winchester Super X3"
L["wep." .. w .. ".name"] = "Super X3"
L["wep." .. w .. ".desc"] = "Civilian sporting shotgun engineered for performance. Long barrel and competition choke offer great accuracy and range but poor handling."
L["wep." .. w .. ".desc.quote"] = "A great choice when it comes to self defense and hunting small game."
L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
L["wep." .. w .. ".credits"] = "Model, Textures & Sound: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "thompson"
L["wep." .. w .. ".name.full"] = "M1A1 Thompson"
L["wep." .. w .. ".name"] = "Thompson"
L["wep." .. w .. ".desc"] = "WW2-era SMG with sturdy wooden furniture. Boasts impressive close-range firepower, but is rather heavy."
L["wep." .. w .. ".desc.quote"] = "\"Eat lead, jerries!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Auto-Ordnance Company"
L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "tt33"
L["wep." .. w .. ".name.full"] = "Tokarev TT-33"
L["wep." .. w .. ".name"] = "TT-33"
L["wep." .. w .. ".desc"] = "Antique pistol from beyond the Iron Curtain. High range and penetration, but has reliability issues due to its age."
L["wep." .. w .. ".desc.quote"] = "\"Perhaps you would prefer to avoid the red tape?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".credits"] = "Model: Mr.Rifleman \nTextures: BuLL5H1T & Mr.Rifleman \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "vz58"
L["wep." .. w .. ".name.full"] = "Sa vz. 58"
L["wep." .. w .. ".name"] = "vz. 58"
L["wep." .. w .. ".desc"] = "High-damage assault rifle with excellent armor piercing capabilities, converted to semi auto for civilian markets."
L["wep." .. w .. ".desc.quote"] = "Despite its looks, it is definitely not an AK."
L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
L["wep." .. w .. ".credits"] = "Model, Textures & Sounds: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "wa2000"
L["wep." .. w .. ".name.full"] = "Walther WA 2000"
L["wep." .. w .. ".name"] = "WA 2000"
L["wep." .. w .. ".desc"] = "Elegant bullpup sniper rifle with high damage and high rate of fire. \nEquipped with a 12x scope by default."
L["wep." .. w .. ".desc.quote"] = "\"Names are for friends, so I don't need one.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

-- Attachments (sd)
L["att.tac_1858_spin.name.full"] = "Cowboy Tricks"
L["att.tac_1858_spin.name"] = "Spin"
L["att.tac_1858_spin.desc"] = "wheeeeeeeeeeeee"

L["att.optic_m1_scope.name.full"] = "M1 Carbine 3.5×24 Scope"
L["att.optic_m1_scope.name"] = "3.5x Scope"
L["att.optic_m1_scope.desc"] = "Optical scope with specialized mount for the M1 Carbine."

L["att.optic_delisle_scope.name.full"] = "De Lisle 4×24 Scope"
L["att.optic_delisle_scope.name"] = "4x Scope"
L["att.optic_delisle_scope.desc"] = "Optical scope with specialized mount for the De Lisle."

L["att.muzz_supp_assassin.name.full"] = "Assassin Suppressor"
L["att.muzz_supp_assassin.name"] = "A. Suppressor"
L["att.muzz_supp_assassin.desc"] = "Extended suppressor improving range significantly at cost of stability."

L["att.ammo_gyrojet_ratshot.name.full"] = "13mm Ratshot Mini-Rockets"
L["att.ammo_gyrojet_ratshot.name"] = "Ratshot"
L["att.ammo_gyrojet_ratshot.desc"] = "Proximity fuse fragmentation mini-rockets. For rodents of unexpected size."

L["att.ammo_gyrojet_pipe.name.full"] = "15mm Boosted Pipe Grenades"
L["att.ammo_gyrojet_pipe.name"] = "Pipe"
L["att.ammo_gyrojet_pipe.desc"] = "Heavy grenades with timed fuse. Direct hits detonate instantly."

L["att.ammo_gyrojet_lv.name.full"] = "11mm Low Velocity Mini-Rockets"
L["att.ammo_gyrojet_lv.name"] = "LV"
L["att.ammo_gyrojet_lv.desc"] = "Projectiles with reduced diameter and velocity, leaving a less visible trail."

L["att.ammo_gyrojet_he.name.full"] = "13mm High-Explosive Mini-Rockets"
L["att.ammo_gyrojet_he.name"] = "HE"
L["att.ammo_gyrojet_he.desc"] = "Projectile with a small explosive charge instead of a bullet head."

L["att.ammo_1858_45colt.name.full"] = "Remington 1858 .45 Colt Conversion"
L["att.ammo_1858_45colt.name"] = ".45 Colt"
L["att.ammo_1858_45colt.desc"] = "Cartridge conversion firing larger, more powerful, but less reliable rounds."

L["att.ammo_1858_36perc.name.full"] = "Remington 1858 .36 Caliber Conversion"
L["att.ammo_1858_36perc.name"] = ".36 Percussion"
L["att.ammo_1858_36perc.desc"] = "Caliber conversion firing smaller rounds with better range."

L["att.procon.yeehaw"] = "yeeeeeeeeeeeeehawwwwwwwwww"