L = {} -- Polish Content Strings by meerfi

///////////////////// -- [[ Special Delivery ]] --
-- Weapons
ws = "tacrp_sd_"
w = ws .. "1022"
-- L["wep." .. w .. ".name.full"] = "Ruger 10/22"
-- L["wep." .. w .. ".name"] = "10/22"
L["wep." .. w .. ".desc"] = "Ultra lekki karabin do strzelania. Wysoce precyzyjny i łatwy w obsłudze, ale jest ledwo śmiertelny, chyba że zdobędzie strzał w głowę."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Assets: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "1858"
-- L["wep." .. w .. ".name.full"] = "Remington 1858 Army"
-- L["wep." .. w .. ".name"] = "Army"
L["wep." .. w .. ".desc"] = "Zabytkowy rewolwer na kapiszony o dużej mocy na krótkim dystansie, ale bardzo wolny w strzelaniu. Odpowiedni do kowbojskiego roleplayu."
L["wep." .. w .. ".desc.quote"] = "\"Podaj whiskey!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington Arms"
-- L["wep." .. w .. ".credits"] = "Assets: Nimrod Hempel (Fistful of Frags) \nAnimations: CyloWalker \nQuickthrow & melee animations: speedonerd"

w = ws .. "aac_hb"
-- L["wep." .. w .. ".name.full"] = "AAC Honey Badger"
-- L["wep." .. w .. ".name"] = "Honey Badger"
L["wep." .. w .. ".desc"] = "Lekki karabin szturmowy z integralnym tłumikiem. Mocny w walce wręcz i nie ma widocznego śladu, ale ma słabe osiągi na dystansie."
-- L["wep." .. w .. ".trivia.manufacturer"] = "AAC"
-- L["wep." .. w .. ".credits"] = "Model: Hyper \nAnimations: Tactical Intervention"

w = ws .. "bizon"
-- L["wep." .. w .. ".name.full"] = "PP-19 Bizon"
-- L["wep." .. w .. ".name"] = "Bizon"
L["wep." .. w .. ".desc"] = "SMG pochodzące z AK z dużym pojemnym magazynkiem spiralnym. Dość słaby, ale łatwy do kontrolowania i obsługi."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Izhmash"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Milo \nSounds: Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "contender"
-- L["wep." .. w .. ".name.full"] = "T/C G2 Contender"
-- L["wep." .. w .. ".name"] = "Contender"
L["wep." .. w .. ".desc"] = "Jednostrzałowy pistolet myśliwski. Precyzyjny, kompaktowy i śmiertelny, więc lepiej, żeby ta jedna runda się liczyła. \nDomyślnie wyposażony w lunetę 6x."
L["wep." .. w .. ".desc.quote"] = "\"Wiesz co mnie denerwuje? Dwie grupy ludzi...\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Thompson/Center"
-- L["wep." .. w .. ".credits"] = "Model: kriboez, Doktor haus \nTextures: cR45h, syncing, tenoyl, Ultimately \nSounds: Doktor haus \nAnimations: 8Z, speedonerd"

w = ws .. "db"
-- L["wep." .. w .. ".name.full"] = "Stoeger Double Defense"
-- L["wep." .. w .. ".name"] = "Double Defense"
L["wep." .. w .. ".desc"] = "Nowoczesna krótka strzelba dwulufowa. Łatwa w obsłudze, niezawodna i śmiertelna w walce wręcz."
L["wep." .. w .. ".desc.quote"] = "\"Eat leaden death, demon.\"" --To be translated
-- L["wep." .. w .. ".trivia.manufacturer"] = "Stoeger"
-- L["wep." .. w .. ".credits"] = "Model: Counter-Strike: Online 2 \nSounds: Navaro & Vunsunta \nAnimations: speedonerd & 8Z"

w = ws .. "delisle"
L["wep." .. w .. ".name.full"] = "Karabin De Lisle"
-- L["wep." .. w .. ".name"] = "De Lisle"
L["wep." .. w .. ".desc"] = "Karabin samopowtarzalny kaliberu pistoletowego z wbudowanym tłumikiem. Jedna z najcichszych broni palnych kiedykolwiek wykonanych, jego pociski subsoniczne nie mają smug, ale poruszają się powoli."
L["wep." .. w .. ".desc.quote"] = "Wystrzelony do Tamizy, nikt go nie usłyszał."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sterling Armaments"
-- L["wep." .. w .. ".credits"] = "Model: RedRougeXIII \nTextures: Storm (lovingly fixed by Unselles) \nAnimations: Tactical Intervention"

w = ws .. "dual_1911"
-- L["wep." .. w .. ".name"] = "Dueling Wyverns"
L["wep." .. w .. ".desc"] = "Para ozdobnych, złotych pistoletów M1911 z wyrytymi wizerunkami wiwern. Mocno uderzają, ale ich niska pojemność może być problematyczna."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Springfield Armory"
-- L["wep." .. w .. ".credits"] = "Model: Schmung \nTextures: Millenia \nAnimations: Tactical Intervention"

w = ws .. "dual_degala"
-- L["wep." .. w .. ".name"] = "Dual Eagles"
L["wep." .. w .. ".desc"] = "Para ozdobnych, złotych Desert Eagles, jakby jeden nie wystarczył. Podwójna szalona moc obalająca, podwójny szalony odrzut."
L["wep." .. w .. ".desc.quote"] = "\"Moja krew... na ich rękach.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Stoke \nTextures: The_Tub & Stoke \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "dual_ppk"
L["wep." .. w .. ".name"] = "Podwójni agenci"
L["wep." .. w .. ".desc"] = "Para tłumionych pistoletów PPK. Szybkie i precyzyjne, ale niska pojemność i przeciętne obrażenia wymagają ostrego oka i dyscypliny spustu."
L["wep." .. w .. ".desc.quote"] = "Lepiej nie wybieraj Oddjoba."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dual_usp"
L["wep." .. w .. ".name"] = "Podwójne mecze"
L["wep." .. w .. ".desc"] = "Para pistoletów zdobytych od pary martwych metrocops. Przyzwoite obrażenia i pojemność, ale ciężkie i wolne do strzelania."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Silvio Dante & Twinke Masta \nTextures: LoneWolf \nAnimations: Tactical Intervention"

w = ws .. "dual_uzis"
L["wep." .. w .. ".name"] = "Podwójne Uzis"
L["wep." .. w .. ".desc"] = "Para pełnoautomatycznych Micro Uzis. Nie wiem, jak oczekujesz trafić cokolwiek z tym wyposażeniem, ale rób, jak uważasz."
L["wep." .. w .. ".desc.quote"] = "\"Uderzę cię tyloma prawami, że będziesz błagać o lewe!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Israel Military Industries"
-- L["wep." .. w .. ".credits"] = "Model: BrainBread 2 \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "dualies"
-- L["wep." .. w .. ".name"] = "Dueling Dragons"
L["wep." .. w .. ".desc"] = "Para spersonalizowanych pistoletów z dwukolorowym wykończeniem i smokami na uchwytach. Szybka obsługa i przyzwoita kontrola odrzutu, ale niska moc obalająca."
L["wep." .. w .. ".desc.quote"] = "\"Puściłem palec ze spustu i to było koniec.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Model: Spydr \nTextures: NCFurious \nAnimations: Tactical Intervention"

w = ws .. "famas"
-- L["wep." .. w .. ".name"] = "FAMAS F1"
L["wep." .. w .. ".desc"] = "Bullpup z ogniem serii o wysokiej szybkostrzelności i świetnej celności, ale ograniczony przez poniżej standardową pojemność magazynka i dość intensywny odrzut. \nMa dwójnóg z tajemniczych francuskich powodów."
-- L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
-- L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "famas_g2"
-- L["wep." .. w .. ".name"] = "FAMAS G2"
-- L["wep." .. w .. ".desc"] = "Bullpup rifle with a blazing fast firerate, used by the French Navy. While capable of automatic fire, using burst-fire or the built-in bipod is recommended."
-- L["wep." .. w .. ".desc.quote"] = "\"God's got a sense of humor, alright.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "GIAT Industries"
-- L["wep." .. w .. ".credits"] = "Model: SnipaMasta \nTextures: SnipaMasta, Fnuxray \nAnimations: speedonerd"

w = ws .. "g3"
-- L["wep." .. w .. ".name.full"] = "HK G3A3"
-- L["wep." .. w .. ".name"] = "G3A3"
L["wep." .. w .. ".desc"] = "Precyzyjny ciężki karabin bojowy z dość znośnym trybem ognia automatycznego, ale wolnym obsługiwaniem."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Firearms: Source \nSounds: Nightmare Mutant & FA:S2 \nAnimations: Tactical Intervention"

w = ws .. "groza"
L["wep." .. w .. ".name.full"] = "OTs-14 \"Groza-4\""
-- L["wep." .. w .. ".name"] = "Groza-4"
L["wep." .. w .. ".desc"] = "Niejasny karabin bullpup wykonany z przekonfigurowanego AK. Słaby, ale ma świetne prowadzenie i stabilność. \nTłumik nie jest integralny, ale działa jako chwyt przedni."
L["wep." .. w .. ".desc.quote"] = "\"Znikaj stąd, stalkerze.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "TsKIB SOO"
-- L["wep." .. w .. ".credits"] = "Model: Teh Snake, edited by speedonerd \nTextures: Teh Snake \nSounds: Teh Snake & speedonerd \nAnimations: speedonerd"

w = ws .. "gyrojet"
L["wep." .. w .. ".name.full"] = "MBA Gyrojet MkI"
-- L["wep." .. w .. ".name"] = "Gyrojet"
L["wep." .. w .. ".desc"] = "Niejasny eksperymentalny pistolet strzelający samonapędzającymi się minirakietami. Obecnie głównie przedmiot kolekcjonerski, amunicja jest potężna, ale niewiarygodna."
L["wep." .. w .. ".desc.quote"] = "\"Z czyjej prywatnej kolekcji to ukradłeś?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "MBAssociates"
-- L["wep." .. w .. ".credits"] = "Model & Textures: RedRougeXIII \nSounds: speedonerd, Tactical Intervention \nAnimations: speedonerd"

w = ws .. "m1carbine"
-- L["wep." .. w .. ".name"] = "M1 Carbine"
L["wep." .. w .. ".desc"] = "Karabin samopowtarzalny z okresu II wojny światowej. Przeznaczony jako broń obronna dla wojsk wsparcia, jest precyzyjny i lekki, ale ma przeciętną moc."
-- L["wep." .. w .. ".desc.quote"] = "\"Flash.\" \"Thunder.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "General Motors"
-- L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "mp40"
-- L["wep." .. w .. ".name.full"] = "Steyr MP40"
-- L["wep." .. w .. ".name"] = "MP40"
L["wep." .. w .. ".desc"] = "SMG z okresu II wojny światowej o niskiej szybkostrzelności i diabelskim profilu odrzutu. Pomimo swojego wieku, nadal pojawia się w wielu strefach wojennych."
L["wep." .. w .. ".desc.quote"] = "\"Hans, twoja kawa jest okropna. Nie będę tego pił.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Steyr-Mannlicher"
-- L["wep." .. w .. ".credits"] = "Model: Soul-Slayer \nTextures: Kimono \nSounds: Futon & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "pkm"
-- L["wep." .. w .. ".name"] = "PKM"
L["wep." .. w .. ".desc"] = "Uniwersalny karabin maszynowy zdolny do intensywnego ognia zaporowego. Wysoka pojemność i obrażenia, ale jest bardzo, bardzo masywny."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Degtyaryov Plant"
-- L["wep." .. w .. ".credits"] = "Assets: Call to Arms \nSounds: NightmareMutant & speedonerd \nAnimations: Tactical Intervention"

w = ws .. "ppk"
-- L["wep." .. w .. ".name.full"] = "Walther PPK"
-- L["wep." .. w .. ".name"] = "PPK"
L["wep." .. w .. ".desc"] = "Kompaktowy, niskopojemnościowy pistolet kieszonkowy, słynny dzięki filmom. Najlepiej nadaje się do obrony na bliskim dystansie."
L["wep." .. w .. ".desc.quote"] = "\"Szokujące. Absolutnie szokujące.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Kimono \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "superx3"
-- L["wep." .. w .. ".name.full"] = "Winchester Super X3"
-- L["wep." .. w .. ".name"] = "Super X3"
L["wep." .. w .. ".desc"] = "Cywilna strzelba sportowa, zaprojektowana z myślą o wydajności. Długa lufa i sportowy czok zapewniają dobrą kontrolę i zasięg, ale słabe prowadzenie."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Winchester Repeating Arms"
-- L["wep." .. w .. ".credits"] = "Model, Textures & Sound: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "thompson"
-- L["wep." .. w .. ".name.full"] = "M1A1 Thompson"
-- L["wep." .. w .. ".name"] = "Thompson"
L["wep." .. w .. ".desc"] = "Pistolet maszynowy z czasów II wojny światowej z solidnymi drewnianymi elementami. Imponująca siła ognia na bliskim dystansie, ale znacznie cięższy niż powinien być."
-- L["wep." .. w .. ".desc.quote"] = "\"Eat lead, jerries!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Auto-Ordnance Company"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "tt33"
-- L["wep." .. w .. ".name.full"] = "Tokarev TT-33"
-- L["wep." .. w .. ".name"] = "TT-33"
L["wep." .. w .. ".desc"] = "Antyczny pistolet zza Żelaznej Kurtyny. Amunicja ma zaskakująco duży cios, ale jest niepewna."
-- L["wep." .. w .. ".desc.quote"] = "\"Perhaps you would prefer to avoid the red tape?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: Mr.Rifleman \nTextures: BuLL5H1T & Mr.Rifleman \nSounds: NightmareMutant \nAnimations: Tactical Intervention"

w = ws .. "vz58"
-- L["wep." .. w .. ".name.full"] = "Sa vz. 58"
-- L["wep." .. w .. ".name"] = "vz. 58"
L["wep." .. w .. ".desc"] = "Karabin szturmowy o wysokim uszkodzeniu z doskonałymi możliwościami przebijania pancerza, przekształcony na półautomatyczny dla rynków cywilnych."
L["wep." .. w .. ".desc.quote"] = "Pomimo wyglądu, to na pewno nie jest AK."
-- L["wep." .. w .. ".trivia.manufacturer"] = "CZ Uherský Brod"
-- L["wep." .. w .. ".credits"] = "Model, Textures & Sounds: No More Room in Hell \nAnimations: Tactical Intervention"

w = ws .. "wa2000"
-- L["wep." .. w .. ".name.full"] = "Walther WA 2000"
-- L["wep." .. w .. ".name"] = "WA 2000"
L["wep." .. w .. ".desc"] = "Elegancki karabin snajperski bullpup o wysokim uszkodzeniu i wysokiej szybkostrzelności. \nDomyślnie wyposażony w lunetę 12x."
L["wep." .. w .. ".desc.quote"] = "\"Imiona są dla przyjaciół, więc nie potrzebuję jednego.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Walther"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: HK & Vunsunta \nAnimations: Tactical Intervention, edited by speedonerd"

-- Attachments (sd)
-- L["att.trigger_dual_uzis_semi.name.full"] = "att.trigger_semi.name.full"
-- L["att.trigger_dual_uzis_semi.name"] = "att.trigger_semi.name"
-- L["att.trigger_dual_uzis_semi.desc"] = "att.trigger_semi.desc"

-- L["att.tac_1858_spin.name.full"] = "Revolver Spin"
-- L["att.tac_1858_spin.name"] = "Spin"
-- L["att.tac_1858_spin.desc"] = "wheeeeeeeeeeeee"

-- L["att.optic_m1_scope.name.full"] = "M1 Carbine 3.5x24 Scope"
-- L["att.optic_m1_scope.name"] = "3.5x Scope"
-- L["att.optic_m1_scope.desc"] = "Optical scope with specialized mount for the M1 Carbine."

-- L["att.optic_delisle_scope.name.full"] = "De Lisle 4x24 Scope"
-- L["att.optic_delisle_scope.name"] = "4x Scope"
-- L["att.optic_delisle_scope.desc"] = "Optical scope with specialized mount for the De Lisle."

-- L["att.muzz_supp_assassin.name.full"] = "Assassin Suppressor"
-- L["att.muzz_supp_assassin.name"] = "A. Suppressor"
-- L["att.muzz_supp_assassin.desc"] = "Extended suppressor improving range significantly at cost of stability."

-- L["att.ammo_gyrojet_ratshot.name.full"] = "13mm Ratshot Mini-Rockets"
-- L["att.ammo_gyrojet_ratshot.name"] = "Ratshot"
-- L["att.ammo_gyrojet_ratshot.desc"] = "Proximity fuse fragmentation mini-rockets. For rodents of unexpected size."

-- L["att.ammo_gyrojet_pipe.name.full"] = "15mm Boosted Pipe Grenades"
-- L["att.ammo_gyrojet_pipe.name"] = "Pipe"
-- L["att.ammo_gyrojet_pipe.desc"] = "Heavy grenades with timed fuse. Direct hits detonate instantly."

-- L["att.ammo_gyrojet_lv.name.full"] = "11mm Low Velocity Mini-Rockets"
-- L["att.ammo_gyrojet_lv.name"] = "LV"
-- L["att.ammo_gyrojet_lv.desc"] = "Projectiles with reduced diameter and velocity, leaving a less visible trail."

-- L["att.ammo_gyrojet_he.name.full"] = "13mm High-Explosive Mini-Rockets"
-- L["att.ammo_gyrojet_he.name"] = "HE"
-- L["att.ammo_gyrojet_he.desc"] = "Projectile with a small explosive charge instead of a bullet head."

-- L["att.ammo_1858_45colt.name.full"] = "Remington 1858 .45 Colt Conversion"
-- L["att.ammo_1858_45colt.name"] = ".45 Colt"
-- L["att.ammo_1858_45colt.desc"] = "Cartridge conversion firing larger, more powerful, but less reliable rounds."

-- L["att.ammo_1858_36perc.name.full"] = "Remington 1858 .36 Caliber Conversion"
-- L["att.ammo_1858_36perc.name"] = ".36 Percussion"
-- L["att.ammo_1858_36perc.desc"] = "Caliber conversion firing smaller rounds with better range."

-- L["att.procon.yeehaw"] = "yeeeeeeeeeeeeehawwwwwwwwww"